# Write your MySQL query statement below
SELECT U.NAME, SUM(T.AMOUNT) AS BALANCE
    FROM USERS U
    JOIN TRANSACTIONS T
    ON U.ACCOUNT = T.ACCOUNT
    GROUP BY U.ACCOUNT
    HAVING BALANCE > 10000;